# PowerShell Function App to Windows on Azure
# Build a PowerShell Function App and deploy it to Azure as a Windows function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-powershell

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '26085b93-8e50-4011-97f4-bd7f631e63e1'

  # Function app name
  functionAppName: 'MyAzureFuncTrigger1'

  # Agent VM image name
  vmImageName: 'windows-2019'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: ArchiveFiles@2
      displayName: 'Archive FunctionApp'
    - task: PublishPipelineArtifact@1
